config/routes.rb
Rails.application.routes.draw do
  get 'reservations/new'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'recipients/new'

  get 'sessions/new'

  root 'static_pages#home'
  get  'dashboard' => 'static_pages#dashboard'
  get 'newsletter' => 'recipients#new'
  get 'signup' => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  post "reservations/:id" => "reservations#show"
  post "hook" => "reservations#hook"
  resources :users
  resources :recipients
  resources :reservations, only: [:create, :destroy, :edit]
  resources :meetings, only: [:create, :destroy, :edit]
  resources :meetings do
    member do
      get 'destroy'
      put 'destroy'
    end
  end
  match "meetings/:id/destroy" => "meetings#destroy", :via => [:get], :as => 'meetings_destroy'
  resources :items, only: [:create, :destroy, :edit]
  resources :items do
    member do
      get 'destroy'
      put 'destroy'
    end
  end
  match "items/:id/destroy" => "items#destroy", :via => [:get], :as => 'items_destroy'
  resources :reservations do
    member do
      get 'confirm_reservation'
      put 'confirm_reservation'
      get 'deny_reservation'
      put 'deny_reservation'
    end
  end
  match "reservations/:id/confirm_reservation" => "reservations#confirm_reservation", :via => [:get], :as => 'reservations_confirm_reservation'
  match "reservations/:id/deny_reservation" => "reservations#deny_reservation", :via => [:get], :as => 'reservations_deny_reservation'
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :users do
    member do
      get 'chefStatus'
      put 'chefStatus'
      get 'activationStatus'
      put 'activationStatus'
      get 'sendmessage'
      put 'sendmessage'
      get 'chefrequest'
      put 'chefrequest'
    end
  end
match "users/:id/chefStatus" => "users#chefStatus", :via => [:get], :as => 'users_chefStatus'
match "users/:id/activationStatus" => "users#activationStatus", :via => [:get], :as => 'users_activationStatus'

match "users/sendmessage" => "users#sendmessage", :via => [:get]
match "chefrequest" => "users#chefrequest", :via => [:get]

  

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reservations, dependent: :destroy
  has_many :items, dependent: :destroy
  has_many :meetings, dependent: :destroy
  attr_accessor :remember_token, :activation_token, :reset_token, :remove_avatar
  before_save   :downcase_email, :delete_avatar, if: ->{ remove_avatar == '1' && !avatar_updated_at_changed? }
  before_create :create_activation_digest
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  has_attached_file :avatar,  :styles => {
      :thumb => "100x100#",
      :small  => "150x150>",
      :medium => "200x200" }, default_url: "Default_:style.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  VALID_ZIPCODE_REGEX = /(^\d{5}$)|(^\d{5}-\d{4}$)/
  validates :zipcode, presence: true, length: { maximum: 10 },
		    format: { with: VALID_ZIPCODE_REGEX }
  validates :food, length: {maximum: 255}
  serialize :messages,Array
  acts_as_mappable :default_units => :miles,
                   :default_formula => :sphere,
                   :distance_field_name => :distance,
                   :lat_column_name => :lat,
                   :lng_column_name => :lng
             	
  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  #add lat and lng to users, have zipcode translated and stored
  def store_location
    loc = Geokit::Geocoders::GoogleGeocoder.geocode "#{self.zipcode}"
    if loc.success
      update_attribute(:lat, loc.lat)
      update_attribute(:lng, loc.lng)
    end
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
  digest = send("#{attribute}_digest")
  return false if digest.nil?
  BCrypt::Password.new(digest).is_password?(token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

  # Add Chef Status.
  def makeChef
    update_attribute(:chef,    true)
  end

  # Remove Chef Status
  def removeChef
    update_attribute(:chef,    false)
  end

  # Send Chef confirmation email
  def send_chef_confirmation_email
    UserMailer.chef_confirmation(@user).deliver_now
  end

  # Send Chef notification of dismissal!
  def send_chef_notification_email
    UserMailer.chef_notification(@user).deliver_now
  end

  # Activates an account.
  def activate
    update_attribute(:activated,    true)
    update_attribute(:activated_at, Time.zone.now)
  end

  # Deactivates an account
  def deactivate
    update_attribute(:activated,    false)
  end

  # Sends activation email.
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  # Sends deactivation email.
  def send_deactivation_email
    UserMailer.account_deactivation(self).deliver_now
  end
  # Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end
  # Returns true if a password reset has expired.
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end
  


private
    # Converts email to all lower-case.
    def downcase_email
      self.email = email.downcase
    end

    # Creates and assigns the activation token and digest.
    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
    # Removes avatar
    def delete_avatar
      self.avatar = nil
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: [:destroy, :activationStatus, :chefStatus]
  # GET /users
  # GET /users.json
  #def index
 #   @users = User.where(admin: false).paginate(page: params[:page], :per_page => 15)
#  end
  
  def index
    if current_user.admin?
      @users = User.where(admin: false).paginate(page: params[:page], :per_page => 15)
    else
      @users = nearyou(params[:zip])
    end
  end
  
  def chefrequest
    sendchefrequest(params[:content])
  end

  def sendchefrequest (content)
    current_user.update_attributes(request: true, chef: true)
    user = User.first
    time = Time.new
    datestamp = time.strftime("%Y-%m-%d %l:%M %P")
    message = ("Sent from #{current_user.name} (#{current_user.email} | ID: #{current_user.id}) at #{datestamp}: \n" + "\n" + content) 
    user.messages.push(message)
    user.save
  end

  def sendmessage
      user = User.find(params[:id])
      messagesender(params[:content], user)
  end


 def messagesender (content, user)
    time = Time.new
    datestamp = time.strftime("%Y-%m-%d %l:%M %P")
    if !current_user.chef?
    message = ("Sent from #{current_user.name} (#{current_user.email}) at #{datestamp}: \n" + "\n" + content + "\n" + "\n Profile: foodmade.co/users/#{current_user.id}")
    else
    message = ("Sent from #{current_user.name} (Chef) at #{datestamp}: \n" + "\n" + content + "\n" + "\n Profile: foodmade.co/users/#{current_user.id}")
    end 
    user.messages.push(message)
    user.save
  end

  def nearyou (zip)

    @chefs = Array.new
    address = Geokit::Geocoders::GoogleGeocoder.geocode "#{zip}"
    @users = User.where(chef: true)
    @users.each do |user|
      if user.chef?
        destination = Geokit::Geocoders::GoogleGeocoder.geocode "#{user.zipcode}"
        if (destination.distance_to(address) < 30)
          @chefs.push(user)
        end
      end
    end
    return @chefs
  end



  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @items = Item.where(user_id: @user.id) 
    @meetings = Meeting.where(user_id: @user.id)
    @reservation = Reservation.create
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
	@user = User.find(params[:id])
        @item = Item.create
        @meeting = Meeting.create
  end
 

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    if @user.save
      #@user.store_location
      @user.send_activation_email
      flash[:success] = "Please check your email to activate your account."
      redirect_to root_url
    else
      render 'new'
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      #@user.store_location
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
  def activationStatus
    @user = User.find(params[:id])
    if !@user.activated?
      @user.activate
      flash[:success] = "#{@user.name} is now activated!" 
      redirect_to "/users?approved=true"
    else 
      @user.deactivate
      flash[:danger] = "#{@user.name} has been deactivated. Notification email has been sent to #{@user.email}!"
      @user.send_deactivation_email
      redirect_to "/users?approved=false"
    end
  end
  def chefStatus
    @user = User.find(params[:id])
    if !@user.chef?
      @user.update_attribute(:chef,    true)
      @user.update_attribute(:request, false)
      flash[:success] = "#{@user.name} is now a chef! Notification email has been sent to #{@user.email}!" 
      @user.messages.push("From the FoodMade Team: \n
      \n You are now a chef! Be sure to update your profile information with what you will cook!")
      @user.save
      UserMailer.chef_confirmation(@user).deliver_now
      redirect_to "/users?approved=true"
    else 
      @user.update_attribute(:chef,    false)
      flash[:danger] = "#{@user.name} is no longer a chef. Notification email has been sent to #{@user.email}!"
      UserMailer.chef_notification(@user).deliver_now
      redirect_to "/users?approved=false"
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
    end
  end




  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar, :remove_avatar, :zipcode, :food, :messages, :menu, :request)
    end
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
end
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
    # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end


        

app/helpers/users_helper.rb
module UsersHelper



end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<% if user.activated? && !user.admin?  %>
<li>
  <%= image_tag user.avatar(:thumb) %>
  <%= link_to user.name, user %>
  | <%= user.zipcode %>
  <% if user.chef? %>
    <mark>CHEF</mark> <%= user.food %>
  <% end %>
</li>
<% end %>

app/views/users/chefrequest.html.erb
  <% flash[:success] = "You are now a chef! Be sure to update your profile with a menu and food type in profile settings." %>
    <script type="text/javascript">
    window.location.href="/dashboard"  // put your correct path in a string here
  </script>

app/views/users/edit.html.erb
<% provide(:title, 'Update Profile') %>

<div class = "well gray ">
<% if current_user.chef? %>
<h1><center><strong>Update Schedule</strong></center></h1>


    <div class="row">
        <div class='col-md-6 col-md-offset-3'>
 <%= form_for(@meeting) do |f| %>
            <%= f.label :time %>
            <%= f.text_field :time, class: 'form-control', id: 'datetimepicker4' %>
        
        <script type="text/javascript">
            $(function () {
                $('#datetimepicker4').datetimepicker();
            });
        </script>
<%= f.label :duration %> (in Minutes)
<%= f.number_field :duration, :class => 'form-control', :step => 'any', :value => "30" %>
<%= f.hidden_field :user_id, :value => @user.id %>
	<br>
      <%= f.submit "Add time!", class: "btn btn-warning" %>
    <% end %>
    </div>
</div>


<h1><center><strong>Update Menu</strong></center></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@item) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control' %>

      <%= f.label :price %>
      <%= f.number_field :price, :class => 'text_field', :step => 0.01 %>

      <%= f.label :picture %>
      <%= f.file_field :avatar %>
      <%= f.hidden_field :user_id, :value => @user.id %>

	<br>
      <%= f.submit "Add item!", class: "btn btn-warning" %>
    <% end %>
</div>
</div>
<% end %>
<br>
<h1><center><strong>Update Profile</strong></center></h1>
<center><%= image_tag @user.avatar (:thumb) %></center>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %> 
      <% if current_user.chef? %>
        <%= f.label :Type_of_food %>
        <%= f.text_field :food, class: 'form-control' %>
        <!---<%= f.label :Menu %> (List items, prices, and any other information about your offered dining experience)
        <%= f.text_area :menu, class: 'form-control' %> --->

      <% end %>

      <%= f.label :zipcode %>
      <%= f.text_field :zipcode, class: 'form-control' %>
      <%= f.label :avatar %>
      <%= f.file_field :avatar %>
        <center>
    <div class="col-sm-offset-2 col-sm-7 ">
      <div class="checkbox">
        <label>
          <%= f.check_box :remove_avatar %> Remove Avatar
	</label>
      </div>
    </div>
  </center>
     <!--- <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %> --->
<br>

      <%= f.submit "Save Changes", class: "btn btn-warning" %>
    <% end %>
	<%= link_to "Reset Password", new_password_reset_path %>
	<br>

	<br>
  </div>
</div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>

<div class = "well gray" >

<h1>Chefs nearby</h1> (50 mile radius)


<ul class="users">
<% if current_user.admin? %>
    <table class="table table-hover">
      <thead>
        <tr>
          <th>User Info</th>
          <th>Admin Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
        <% if !user.admin? %>
          <tr>
            <td>
              <%= image_tag user.avatar(:thumb) %>
              <%= link_to user.name, user %> <%= user.id %>
	      <% if user.request? %>
                <strong><mark>REQUEST TO BE CHEF</mark></strong>
              <% end %>
              <% if !user.activated? %>
                <strong><mark>NOT ACTIVATED</mark></strong>
              <% end %>
              <% if user.chef? %>
	        <strong><mark>CHEF</mark></strong>
              <% end %>
            </td>
            <td>
              <% if !current_user?(user) %> 
                <% if user.chef? %>
                  <%= link_to "Dismiss chef", {:controller => "users", :id => user.id, :action => "chefStatus"}, {:method => :put, :chef => false,
data: { confirm: "REMOVE chef status from #{user.name}?" }, class: "btn btn-sm btn-info"} %>
                <% else %> 
                  <%= link_to "Make chef", {:controller => "users", :id => user.id, :action => "chefStatus"}, {:method => :put, :chef => true,
data: { confirm: "ADD chef status to #{user.name}?" }, class: "btn btn-sm btn-info"} %>
                <% end %>
		<% if user.activated? %>
			<%= link_to "Deactivate", {:controller => "users", :id => user.id, :action => "activationStatus"}, {:method => :put, :activated => false,
data: { confirm: "DEACTIVATE #{user.name}?" }, class: "btn btn-sm btn-warning"} %>
		<% else %>
			<%= link_to "Activate", {:controller => "users", :id => user.id, :action => "activationStatus"}, {:method => :put, :activated => true,
data: { confirm: "ACTIVATE #{user.name}?" }, class: "btn btn-sm btn-warning"} %>
		<% end %>
                <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "Delete #{user.name}?" }, class: "btn btn-sm btn-danger" %>
               <% end %>
             </td>
           </tr>
         <% end %>
         <% end %>
       </tbody>
     </table>
<% else %>
  <%= render @users %>
<% end %>
</ul>

</div>

app/views/users/nearyou.html.erb
<% provide(:title, 'Close to you') %>

<div class = "well gray" >

<h1>Users</h1>
<%= will_paginate %>
<ul class="users">
<% @users.each do |user| %>
<% if user.activated? && !user.admin?  %>
<li>
  <%= image_tag user.avatar(:thumb) %>
  <%= link_to user.name, user %>

  <% if user.chef? %>
    <mark>CHEF</mark>
  <% end %>
</li>
<% end %>
<% end %>
</ul>
<%= will_paginate %>
</div>

app/views/users/new.html.erb
<body class = "homepage">
<% provide(:title, 'Sign up') %>

<div class = "well  transparent ">
<h1><center><strong>Sign up</strong></center></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :zipcode %>
      <%= f.text_field :zipcode, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.label :avatar %>
      <%= f.file_field :avatar %>
	<br>
      <%= f.submit "Create my account", class: "btn btn-warning" %>
    <% end %>
	
	<br>
  </div>
</div>
</div>
</body>

app/views/users/sendmessage.html.erb
  <% flash[:success] = "Message sent." %>
    <script type="text/javascript">
    window.location.href="/dashboard"  // put your correct path in a string here
  </script>

app/views/users/show.html.erb
  <script>
function Total(qty,ud,total,value){
 qty=document.getElementById(qty);
 ud>0?qty.value++:qty.value--;
 if (ud>0) {
    tot.value=parseFloat(tot.value)+parseFloat(value);
 } else if (qty.value >= 0) {
 tot.value=parseFloat(tot.value)-parseFloat(value);
 }
 tot.value = toFixed(tot.value, 2);
 qty.value=Math.max(qty.value,0);
 document.getElementById(total).value=qty.value*value;
 
}

function toFixed(value, precision) {
    var precision = precision || 0,
        power = Math.pow(10, precision),
        absValue = Math.abs(Math.round(value * power)),
        result = (value < 0 ? '-' : '') + String(Math.floor(absValue / power));

    if (precision > 0) {
        var fraction = String(absValue % power),
            padding = new Array(Math.max(precision - fraction.length, 0) + 1).join('0');
        result += '.' + padding + fraction;
    }
    return result;
}



  </script>
   
<div class = "well gray">
<% provide(:title, @user.name) %>

	<center>
       <%= image_tag @user.avatar(:small) %>
	
	<br>
	<h3>
	
	<%= @user.name %>
	</h3>
</center>
<% if @user.chef? %>
<h2> Menu </h2>
<div id="purhcaseForm">
	 <form id="purchase">
 <table class="table table-hover">
    <thead>
      <tr>
        <th>Picture</th>
        <th>Name</th>
        <th>Description</th>
        <th>Price</th>
        <th>Quantity</th>
      </tr>
    </thead>
    <tbody>
<% @items.each do |item| %>
 <tr>
  <td>
  <%= image_tag item.avatar(:thumb) %>
  </td>
  <td>
  <%= item.name %>
  </td>
  <td>
  <%= item.description %>
   </td>
  <td>
  $<%= item.price %>
  </td>
  <td>
 
 <div class="row">
    <div class="col-sm-2" ><input type='button' name='subtract' onclick='Total("qty<%= item.id %>",-1,"total<%= item.id %>","<%= item.price %>");' value='-' class='btn btn-sm'/></div>
    <div class="col-sm-2" ><input type='button' name='add' onclick='Total("qty<%= item.id %>",1,"total<%= item.id %>","<%= item.price %>");' value='+' class='btn btn-sm'/></div>
    <div class="col-sm-2" >		 <input type='text' name='qty<%= item.id %>' id='qty<%= item.id %>' readonly=true value="0" class='well-sm' /></div>
  </div>
</td>
<td>
 <% if @user == current_user %>
    <%= link_to "Delete", {:controller => "items", :id => item.id, :action => "destroy"}, {:method => :put, :existence => false,
data: { confirm: "Delete #{item.name}?" }, class: "btn btn-sm btn-warning"} %>
  <% end %>
</td>
</tr>
<% end %>
</tbody>
</table>
<center>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
 Total Price (USD):

</div>
</div>
</center>
      </form>
</div>
<% end %>

	<% if logged_in? %>
<h2> Make a Reservation </h2>
<center>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@reservation) do |f| %>
      

      <%= f.label :time %>
<%= f.collection_select :time, @meetings.all, :time, :description, {prompt: "Select a time"}, {class: "form-control"} %>
      <%= f.label :order %>
      <%= f.text_area :order, class: 'form-control' %>

      <%= f.label :price %>
      (USD)<%= f.number_field :price, :class => 'form-control', :step => 'any', :id => 'tot', :value => "0" %>

      <%= f.hidden_field :user_id, :value => @user.id %>

	<br>
      <%= f.submit "Send Reservation!", class: "btn btn-warning" %>
    <% end %>
	
	<br>
  </div>
</div>


<br>
<!---<%= form_tag({controller: "users", action: "sendmessage"}, method: "get") do %>
    <%= label_tag(:content, "Send message:") %> 
    <%= text_area_tag(:content)  %>
    <%= submit_tag("Send") %>
<% end %> --->

<% end %>
<p> Profiles are under development. Here, people will be able to see your preferences, reviews, and much more!</p>
   </center>

</div>