config/routes.rb
Rails.application.routes.draw do
  get 'reservations/new'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'recipients/new'

  get 'sessions/new'

  root 'static_pages#home'
  get  'dashboard' => 'static_pages#dashboard'
  get 'newsletter' => 'recipients#new'
  get 'signup' => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  post "reservations/:id" => "reservations#show"
  post "hook" => "reservations#hook"
  resources :users
  resources :recipients
  resources :reservations, only: [:create, :destroy, :edit]
  resources :meetings, only: [:create, :destroy, :edit]
  resources :meetings do
    member do
      get 'destroy'
      put 'destroy'
    end
  end
  match "meetings/:id/destroy" => "meetings#destroy", :via => [:get], :as => 'meetings_destroy'
  resources :items, only: [:create, :destroy, :edit]
  resources :items do
    member do
      get 'destroy'
      put 'destroy'
    end
  end
  match "items/:id/destroy" => "items#destroy", :via => [:get], :as => 'items_destroy'
  resources :reservations do
    member do
      get 'confirm_reservation'
      put 'confirm_reservation'
      get 'deny_reservation'
      put 'deny_reservation'
    end
  end
  match "reservations/:id/confirm_reservation" => "reservations#confirm_reservation", :via => [:get], :as => 'reservations_confirm_reservation'
  match "reservations/:id/deny_reservation" => "reservations#deny_reservation", :via => [:get], :as => 'reservations_deny_reservation'
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :users do
    member do
      get 'chefStatus'
      put 'chefStatus'
      get 'activationStatus'
      put 'activationStatus'
      get 'sendmessage'
      put 'sendmessage'
      get 'chefrequest'
      put 'chefrequest'
    end
  end
match "users/:id/chefStatus" => "users#chefStatus", :via => [:get], :as => 'users_chefStatus'
match "users/:id/activationStatus" => "users#activationStatus", :via => [:get], :as => 'users_activationStatus'

match "users/sendmessage" => "users#sendmessage", :via => [:get]
match "chefrequest" => "users#chefrequest", :via => [:get]

  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small><center></small</center>
</footer>

app/views/layouts/_header.html.erb
  <header class ="navbar navbar-default  navbar-fixed-top">
      <div class="container">
        <% if logged_in? %>
        <%= link_to "FoodMade", dashboard_path , id: "logo" %>
        <nav>

          <ul class="nav navbar-nav navbar-right">

	  <!---<li><%= link_to "Users", users_path %></li>--->
          

<li><%= link_to "Home", dashboard_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
<!---<div class="col-sm-1 col-md-5 ">
        <form class="navbar-form" role="search">
        <div class="input-group">
            <input type="text" class="form-control" placeholder="Search" name="srch-term" id="srch-term">
            <div class="input-group-btn">
                <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
            </div>
        </div>
        </form>
        </div>--->
        <% else %>
        <%= link_to "FoodMade", root_path , id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",  root_path %></li>
         <li><%= link_to "Log in", login_path %></li>
	  <li><%= link_to "Sign up", signup_path %></li>
        <% end %>
          </ul>
        </li>
         
       
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<%= favicon_link_tag 'favicon.ico' %>
<title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
	      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
     <!--- <%= debug(params) if Rails.env.development? %> --->
    </div>
  </body>
</html>